[package]
name = "md-tools"
version = "0.1.0"
authors = ["genshen <genshenchu@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
libc = "0.2"

[build-dependencies]
cc = "1.0"
