[build]
# Target musl-libc by default when running Cargo.
# target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "x86_64-linux-musl-gcc"

#[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"
# if with error "undefined reference to `_encode_pointer'": see https://github.com/rust-lang/rust/issues/32859#issuecomment-573423629
# and https://github.com/rust-lang/rust/issues/36710#issuecomment-364623950

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-framework CoreFoundation -framework Security"]
# see also: https://github.com/shazow/gohttplib/issues/1
