name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.50.0

    - name: Build
      run: cargo build --release --verbose
#     - name: Run tests
#       run: cargo test --verbose
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: md-tools-latest
        path: target/release/md-tools
